name: weather_app_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-210.4.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  json_annotation: ^4.8.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
   - assets/icons/