Map<String, dynamic> jsonExample = {
  "location": {
    "name": "Thiruvananthapuram",
    "region": "Kerala",
    "country": "India",
    "lat": 8.51,
    "lon": 76.96,
    "tz_id": "Asia/Kolkata",
    "localtime_epoch": 1702192682,
    "localtime": "2023-12-10 12:48"
  },
  "current": {
    "last_updated_epoch": 1702192500,
    "last_updated": "2023-12-10 12:45",
    "temp_c": 32.0,
    "temp_f": 89.6,
    "is_day": 1,
    "condition": {
      "text": "Partly cloudy",
      "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
      "code": 1003
    },
    "wind_mph": 5.6,
    "wind_kph": 9.0,
    "wind_degree": 190,
    "wind_dir": "S",
    "pressure_mb": 1009.0,
    "pressure_in": 29.8,
    "precip_mm": 0.0,
    "precip_in": 0.0,
    "humidity": 71,
    "cloud": 75,
    "feelslike_c": 35.8,
    "feelslike_f": 96.4,
    "vis_km": 6.0,
    "vis_miles": 3.0,
    "uv": 8.0,
    "gust_mph": 10.1,
    "gust_kph": 16.2
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2023-12-10",
        "date_epoch": 1702166400,
        "day": {
          "maxtemp_c": 32.6,
          "maxtemp_f": 90.6,
          "mintemp_c": 24.0,
          "mintemp_f": 75.2,
          "avgtemp_c": 27.4,
          "avgtemp_f": 81.3,
          "maxwind_mph": 8.3,
          "maxwind_kph": 13.3,
          "totalprecip_mm": 0.33,
          "totalprecip_in": 0.01,
          "totalsnow_cm": 0.0,
          "avgvis_km": 10.0,
          "avgvis_miles": 6.0,
          "avghumidity": 77.0,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 89,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Patchy rain possible",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "code": 1063
          },
          "uv": 6.0
        },
        "astro": {
          "sunrise": "06:25 AM",
          "sunset": "06:04 PM",
          "moonrise": "03:47 AM",
          "moonset": "03:48 PM",
          "moon_phase": "Waning Crescent",
          "moon_illumination": 10,
          "is_moon_up": 1,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1702146600,
            "time": "2023-12-10 00:00",
            "temp_c": 25.1,
            "temp_f": 77.2,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 25,
            "wind_dir": "NNE",
            "pressure_mb": 1010.0,
            "pressure_in": 29.82,
            "precip_mm": 0.01,
            "precip_in": 0.0,
            "humidity": 90,
            "cloud": 70,
            "feelslike_c": 27.9,
            "feelslike_f": 82.3,
            "windchill_c": 25.1,
            "windchill_f": 77.2,
            "heatindex_c": 27.9,
            "heatindex_f": 82.3,
            "dewpoint_c": 23.3,
            "dewpoint_f": 74.0,
            "will_it_rain": 0,
            "chance_of_rain": 68,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 7.2,
            "gust_kph": 11.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1702150200,
            "time": "2023-12-10 01:00",
            "temp_c": 24.9,
            "temp_f": 76.9,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 34,
            "wind_dir": "NE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.8,
            "precip_mm": 0.17,
            "precip_in": 0.01,
            "humidity": 90,
            "cloud": 81,
            "feelslike_c": 27.6,
            "feelslike_f": 81.7,
            "windchill_c": 24.9,
            "windchill_f": 76.9,
            "heatindex_c": 27.6,
            "heatindex_f": 81.7,
            "dewpoint_c": 23.1,
            "dewpoint_f": 73.6,
            "will_it_rain": 1,
            "chance_of_rain": 78,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 7.2,
            "gust_kph": 11.5,
            "uv": 1.0
          },
          {
            "time_epoch": 1702153800,
            "time": "2023-12-10 02:00",
            "temp_c": 24.3,
            "temp_f": 75.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 49,
            "wind_dir": "NE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.79,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 88,
            "cloud": 15,
            "feelslike_c": 26.6,
            "feelslike_f": 79.9,
            "windchill_c": 24.3,
            "windchill_f": 75.7,
            "heatindex_c": 26.6,
            "heatindex_f": 79.9,
            "dewpoint_c": 22.2,
            "dewpoint_f": 71.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.9,
            "gust_kph": 11.1,
            "uv": 1.0
          },
          {
            "time_epoch": 1702157400,
            "time": "2023-12-10 03:00",
            "temp_c": 24.1,
            "temp_f": 75.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 62,
            "wind_dir": "ENE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.78,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 88,
            "cloud": 13,
            "feelslike_c": 26.4,
            "feelslike_f": 79.5,
            "windchill_c": 24.1,
            "windchill_f": 75.4,
            "heatindex_c": 26.4,
            "heatindex_f": 79.5,
            "dewpoint_c": 22.0,
            "dewpoint_f": 71.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.0,
            "gust_kph": 9.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1702161000,
            "time": "2023-12-10 04:00",
            "temp_c": 24.0,
            "temp_f": 75.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 74,
            "wind_dir": "ENE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.79,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 88,
            "cloud": 17,
            "feelslike_c": 26.2,
            "feelslike_f": 79.2,
            "windchill_c": 24.0,
            "windchill_f": 75.2,
            "heatindex_c": 26.2,
            "heatindex_f": 79.2,
            "dewpoint_c": 21.9,
            "dewpoint_f": 71.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.0,
            "gust_kph": 9.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1702164600,
            "time": "2023-12-10 05:00",
            "temp_c": 24.0,
            "temp_f": 75.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 61,
            "wind_dir": "ENE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.8,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 88,
            "cloud": 15,
            "feelslike_c": 26.2,
            "feelslike_f": 79.2,
            "windchill_c": 24.0,
            "windchill_f": 75.2,
            "heatindex_c": 26.2,
            "heatindex_f": 79.2,
            "dewpoint_c": 21.9,
            "dewpoint_f": 71.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.0,
            "gust_kph": 9.7,
            "uv": 1.0
          },
          {
            "time_epoch": 1702168200,
            "time": "2023-12-10 06:00",
            "temp_c": 24.0,
            "temp_f": 75.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 57,
            "wind_dir": "ENE",
            "pressure_mb": 1010.0,
            "pressure_in": 29.82,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 88,
            "cloud": 17,
            "feelslike_c": 26.3,
            "feelslike_f": 79.3,
            "windchill_c": 24.0,
            "windchill_f": 75.2,
            "heatindex_c": 26.3,
            "heatindex_f": 79.3,
            "dewpoint_c": 21.9,
            "dewpoint_f": 71.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.0,
            "gust_kph": 9.7,
            "uv": 6.0
          },
          {
            "time_epoch": 1702171800,
            "time": "2023-12-10 07:00",
            "temp_c": 25.5,
            "temp_f": 77.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.9,
            "wind_kph": 4.7,
            "wind_degree": 67,
            "wind_dir": "ENE",
            "pressure_mb": 1010.0,
            "pressure_in": 29.84,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 84,
            "cloud": 15,
            "feelslike_c": 28.1,
            "feelslike_f": 82.6,
            "windchill_c": 25.5,
            "windchill_f": 78.0,
            "heatindex_c": 28.1,
            "heatindex_f": 82.6,
            "dewpoint_c": 22.6,
            "dewpoint_f": 72.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.5,
            "gust_kph": 7.3,
            "uv": 7.0
          },
          {
            "time_epoch": 1702175400,
            "time": "2023-12-10 08:00",
            "temp_c": 27.4,
            "temp_f": 81.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 71,
            "wind_dir": "ENE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.86,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 75,
            "cloud": 13,
            "feelslike_c": 30.5,
            "feelslike_f": 86.9,
            "windchill_c": 27.4,
            "windchill_f": 81.4,
            "heatindex_c": 30.5,
            "heatindex_f": 86.9,
            "dewpoint_c": 22.7,
            "dewpoint_f": 72.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.2,
            "gust_kph": 6.7,
            "uv": 7.0
          },
          {
            "time_epoch": 1702179000,
            "time": "2023-12-10 09:00",
            "temp_c": 29.5,
            "temp_f": 85.0,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 86,
            "wind_dir": "E",
            "pressure_mb": 1011.0,
            "pressure_in": 29.86,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 66,
            "cloud": 20,
            "feelslike_c": 33.1,
            "feelslike_f": 91.5,
            "windchill_c": 29.5,
            "windchill_f": 85.0,
            "heatindex_c": 33.1,
            "heatindex_f": 91.5,
            "dewpoint_c": 22.4,
            "dewpoint_f": 72.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 7.0
          },
          {
            "time_epoch": 1702182600,
            "time": "2023-12-10 10:00",
            "temp_c": 31.3,
            "temp_f": 88.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 101,
            "wind_dir": "ESE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.85,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 59,
            "cloud": 15,
            "feelslike_c": 35.4,
            "feelslike_f": 95.8,
            "windchill_c": 31.3,
            "windchill_f": 88.4,
            "heatindex_c": 35.4,
            "heatindex_f": 95.8,
            "dewpoint_c": 22.2,
            "dewpoint_f": 72.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 2.6,
            "gust_kph": 4.1,
            "uv": 8.0
          },
          {
            "time_epoch": 1702186200,
            "time": "2023-12-10 11:00",
            "temp_c": 32.4,
            "temp_f": 90.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 174,
            "wind_dir": "S",
            "pressure_mb": 1010.0,
            "pressure_in": 29.83,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 54,
            "cloud": 15,
            "feelslike_c": 36.8,
            "feelslike_f": 98.3,
            "windchill_c": 32.4,
            "windchill_f": 90.4,
            "heatindex_c": 36.8,
            "heatindex_f": 98.3,
            "dewpoint_c": 22.1,
            "dewpoint_f": 71.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 2.6,
            "gust_kph": 4.1,
            "uv": 8.0
          },
          {
            "time_epoch": 1702189800,
            "time": "2023-12-10 12:00",
            "temp_c": 32.0,
            "temp_f": 89.6,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 5.6,
            "wind_kph": 9.0,
            "wind_degree": 190,
            "wind_dir": "S",
            "pressure_mb": 1009.0,
            "pressure_in": 29.8,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 71,
            "cloud": 75,
            "feelslike_c": 36.9,
            "feelslike_f": 98.5,
            "windchill_c": 32.6,
            "windchill_f": 90.6,
            "heatindex_c": 36.9,
            "heatindex_f": 98.5,
            "dewpoint_c": 22.0,
            "dewpoint_f": 71.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 6.0,
            "vis_miles": 3.0,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 8.0
          },
          {
            "time_epoch": 1702193400,
            "time": "2023-12-10 13:00",
            "temp_c": 32.3,
            "temp_f": 90.1,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 7.2,
            "wind_kph": 11.5,
            "wind_degree": 221,
            "wind_dir": "SW",
            "pressure_mb": 1008.0,
            "pressure_in": 29.76,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 56,
            "cloud": 46,
            "feelslike_c": 36.8,
            "feelslike_f": 98.3,
            "windchill_c": 32.3,
            "windchill_f": 90.1,
            "heatindex_c": 36.8,
            "heatindex_f": 98.3,
            "dewpoint_c": 22.4,
            "dewpoint_f": 72.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.2,
            "gust_kph": 13.2,
            "uv": 8.0
          },
          {
            "time_epoch": 1702197000,
            "time": "2023-12-10 14:00",
            "temp_c": 31.0,
            "temp_f": 87.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 219,
            "wind_dir": "SW",
            "pressure_mb": 1007.0,
            "pressure_in": 29.74,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 62,
            "cloud": 23,
            "feelslike_c": 35.6,
            "feelslike_f": 96.0,
            "windchill_c": 31.0,
            "windchill_f": 87.9,
            "heatindex_c": 35.6,
            "heatindex_f": 96.0,
            "dewpoint_c": 22.9,
            "dewpoint_f": 73.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.5,
            "gust_kph": 15.3,
            "uv": 8.0
          },
          {
            "time_epoch": 1702200600,
            "time": "2023-12-10 15:00",
            "temp_c": 30.0,
            "temp_f": 85.9,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 216,
            "wind_dir": "SW",
            "pressure_mb": 1007.0,
            "pressure_in": 29.75,
            "precip_mm": 0.13,
            "precip_in": 0.01,
            "humidity": 67,
            "cloud": 83,
            "feelslike_c": 34.3,
            "feelslike_f": 93.8,
            "windchill_c": 30.0,
            "windchill_f": 85.9,
            "heatindex_c": 34.3,
            "heatindex_f": 93.8,
            "dewpoint_c": 23.2,
            "dewpoint_f": 73.8,
            "will_it_rain": 1,
            "chance_of_rain": 84,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 7.7,
            "gust_kph": 12.4,
            "uv": 6.0
          },
          {
            "time_epoch": 1702204200,
            "time": "2023-12-10 16:00",
            "temp_c": 29.7,
            "temp_f": 85.5,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 207,
            "wind_dir": "SSW",
            "pressure_mb": 1008.0,
            "pressure_in": 29.76,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 68,
            "cloud": 35,
            "feelslike_c": 33.9,
            "feelslike_f": 93.0,
            "windchill_c": 29.7,
            "windchill_f": 85.5,
            "heatindex_c": 33.9,
            "heatindex_f": 93.0,
            "dewpoint_c": 23.2,
            "dewpoint_f": 73.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 5.9,
            "gust_kph": 9.5,
            "uv": 7.0
          },
          {
            "time_epoch": 1702207800,
            "time": "2023-12-10 17:00",
            "temp_c": 28.3,
            "temp_f": 83.0,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 221,
            "wind_dir": "SW",
            "pressure_mb": 1009.0,
            "pressure_in": 29.78,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 76,
            "cloud": 31,
            "feelslike_c": 32.3,
            "feelslike_f": 90.2,
            "windchill_c": 28.3,
            "windchill_f": 83.0,
            "heatindex_c": 32.3,
            "heatindex_f": 90.2,
            "dewpoint_c": 23.6,
            "dewpoint_f": 74.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 5.7,
            "gust_kph": 9.2,
            "uv": 7.0
          },
          {
            "time_epoch": 1702211400,
            "time": "2023-12-10 18:00",
            "temp_c": 26.8,
            "temp_f": 80.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.5,
            "wind_kph": 4.0,
            "wind_degree": 248,
            "wind_dir": "WSW",
            "pressure_mb": 1009.0,
            "pressure_in": 29.8,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 80,
            "cloud": 24,
            "feelslike_c": 29.9,
            "feelslike_f": 85.8,
            "windchill_c": 26.8,
            "windchill_f": 80.2,
            "heatindex_c": 29.9,
            "heatindex_f": 85.8,
            "dewpoint_c": 23.1,
            "dewpoint_f": 73.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.4,
            "gust_kph": 7.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1702215000,
            "time": "2023-12-10 19:00",
            "temp_c": 26.5,
            "temp_f": 79.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 285,
            "wind_dir": "WNW",
            "pressure_mb": 1010.0,
            "pressure_in": 29.83,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 81,
            "cloud": 22,
            "feelslike_c": 29.4,
            "feelslike_f": 85.0,
            "windchill_c": 26.5,
            "windchill_f": 79.6,
            "heatindex_c": 29.4,
            "heatindex_f": 85.0,
            "dewpoint_c": 23.0,
            "dewpoint_f": 73.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 2.4,
            "gust_kph": 3.9,
            "uv": 1.0
          },
          {
            "time_epoch": 1702218600,
            "time": "2023-12-10 20:00",
            "temp_c": 26.2,
            "temp_f": 79.2,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 0.7,
            "wind_kph": 1.1,
            "wind_degree": 346,
            "wind_dir": "NNW",
            "pressure_mb": 1011.0,
            "pressure_in": 29.85,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 82,
            "cloud": 36,
            "feelslike_c": 29.1,
            "feelslike_f": 84.4,
            "windchill_c": 26.2,
            "windchill_f": 79.2,
            "heatindex_c": 29.1,
            "heatindex_f": 84.4,
            "dewpoint_c": 23.0,
            "dewpoint_f": 73.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.2,
            "gust_kph": 1.9,
            "uv": 1.0
          },
          {
            "time_epoch": 1702222200,
            "time": "2023-12-10 21:00",
            "temp_c": 26.0,
            "temp_f": 78.7,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 1.8,
            "wind_kph": 2.9,
            "wind_degree": 41,
            "wind_dir": "NE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.87,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 83,
            "cloud": 36,
            "feelslike_c": 28.7,
            "feelslike_f": 83.7,
            "windchill_c": 26.0,
            "windchill_f": 78.7,
            "heatindex_c": 28.7,
            "heatindex_f": 83.7,
            "dewpoint_c": 22.9,
            "dewpoint_f": 73.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.2,
            "gust_kph": 5.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1702225800,
            "time": "2023-12-10 22:00",
            "temp_c": 25.6,
            "temp_f": 78.1,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 2.5,
            "wind_kph": 4.0,
            "wind_degree": 33,
            "wind_dir": "NNE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.86,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 85,
            "cloud": 25,
            "feelslike_c": 28.3,
            "feelslike_f": 82.9,
            "windchill_c": 25.6,
            "windchill_f": 78.1,
            "heatindex_c": 28.3,
            "heatindex_f": 82.9,
            "dewpoint_c": 22.8,
            "dewpoint_f": 73.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.5,
            "gust_kph": 7.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1702229400,
            "time": "2023-12-10 23:00",
            "temp_c": 25.4,
            "temp_f": 77.6,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 2.5,
            "wind_kph": 4.0,
            "wind_degree": 26,
            "wind_dir": "NNE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.85,
            "precip_mm": 0.01,
            "precip_in": 0.0,
            "humidity": 85,
            "cloud": 70,
            "feelslike_c": 28.0,
            "feelslike_f": 82.3,
            "windchill_c": 25.4,
            "windchill_f": 77.6,
            "heatindex_c": 28.0,
            "heatindex_f": 82.3,
            "dewpoint_c": 22.7,
            "dewpoint_f": 72.9,
            "will_it_rain": 1,
            "chance_of_rain": 89,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.5,
            "gust_kph": 7.3,
            "uv": 1.0
          }
        ]
      },
      {
        "date": "2023-12-11",
        "date_epoch": 1702252800,
        "day": {
          "maxtemp_c": 32.4,
          "maxtemp_f": 90.3,
          "mintemp_c": 24.3,
          "mintemp_f": 75.7,
          "avgtemp_c": 27.1,
          "avgtemp_f": 80.8,
          "maxwind_mph": 6.3,
          "maxwind_kph": 10.1,
          "totalprecip_mm": 1.49,
          "totalprecip_in": 0.06,
          "totalsnow_cm": 0.0,
          "avgvis_km": 9.6,
          "avgvis_miles": 5.0,
          "avghumidity": 77.0,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 89,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Patchy rain possible",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "code": 1063
          },
          "uv": 6.0
        },
        "astro": {
          "sunrise": "06:26 AM",
          "sunset": "06:04 PM",
          "moonrise": "04:39 AM",
          "moonset": "04:35 PM",
          "moon_phase": "Waning Crescent",
          "moon_illumination": 5,
          "is_moon_up": 1,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1702233000,
            "time": "2023-12-11 00:00",
            "temp_c": 25.1,
            "temp_f": 77.2,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 43,
            "wind_dir": "NE",
            "pressure_mb": 1010.0,
            "pressure_in": 29.84,
            "precip_mm": 0.01,
            "precip_in": 0.0,
            "humidity": 86,
            "cloud": 84,
            "feelslike_c": 27.6,
            "feelslike_f": 81.7,
            "windchill_c": 25.1,
            "windchill_f": 77.2,
            "heatindex_c": 27.6,
            "heatindex_f": 81.7,
            "dewpoint_c": 22.6,
            "dewpoint_f": 72.6,
            "will_it_rain": 1,
            "chance_of_rain": 85,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 5.8,
            "gust_kph": 9.3,
            "uv": 1.0
          },
          {
            "time_epoch": 1702236600,
            "time": "2023-12-11 01:00",
            "temp_c": 24.9,
            "temp_f": 76.9,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 60,
            "wind_dir": "ENE",
            "pressure_mb": 1010.0,
            "pressure_in": 29.81,
            "precip_mm": 0.09,
            "precip_in": 0.0,
            "humidity": 86,
            "cloud": 79,
            "feelslike_c": 27.3,
            "feelslike_f": 81.2,
            "windchill_c": 24.9,
            "windchill_f": 76.9,
            "heatindex_c": 27.3,
            "heatindex_f": 81.2,
            "dewpoint_c": 22.3,
            "dewpoint_f": 72.2,
            "will_it_rain": 1,
            "chance_of_rain": 84,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.2,
            "gust_kph": 10.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1702240200,
            "time": "2023-12-11 02:00",
            "temp_c": 24.7,
            "temp_f": 76.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 70,
            "wind_dir": "ENE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.79,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 86,
            "cloud": 21,
            "feelslike_c": 27.1,
            "feelslike_f": 80.7,
            "windchill_c": 24.7,
            "windchill_f": 76.5,
            "heatindex_c": 27.1,
            "heatindex_f": 80.7,
            "dewpoint_c": 22.2,
            "dewpoint_f": 72.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.7,
            "gust_kph": 10.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1702243800,
            "time": "2023-12-11 03:00",
            "temp_c": 24.6,
            "temp_f": 76.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 67,
            "wind_dir": "ENE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.79,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 86,
            "cloud": 17,
            "feelslike_c": 26.8,
            "feelslike_f": 80.3,
            "windchill_c": 24.6,
            "windchill_f": 76.2,
            "heatindex_c": 26.8,
            "heatindex_f": 80.3,
            "dewpoint_c": 22.1,
            "dewpoint_f": 71.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.7,
            "gust_kph": 10.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1702247400,
            "time": "2023-12-11 04:00",
            "temp_c": 24.5,
            "temp_f": 76.0,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 62,
            "wind_dir": "ENE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.79,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 86,
            "cloud": 15,
            "feelslike_c": 26.7,
            "feelslike_f": 80.1,
            "windchill_c": 24.5,
            "windchill_f": 76.0,
            "heatindex_c": 26.7,
            "heatindex_f": 80.1,
            "dewpoint_c": 22.0,
            "dewpoint_f": 71.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.3,
            "gust_kph": 10.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1702251000,
            "time": "2023-12-11 05:00",
            "temp_c": 24.4,
            "temp_f": 75.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 65,
            "wind_dir": "ENE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.81,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 86,
            "cloud": 14,
            "feelslike_c": 26.6,
            "feelslike_f": 79.9,
            "windchill_c": 24.4,
            "windchill_f": 75.9,
            "heatindex_c": 26.6,
            "heatindex_f": 79.9,
            "dewpoint_c": 21.9,
            "dewpoint_f": 71.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.7,
            "gust_kph": 10.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1702254600,
            "time": "2023-12-11 06:00",
            "temp_c": 24.3,
            "temp_f": 75.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 69,
            "wind_dir": "ENE",
            "pressure_mb": 1010.0,
            "pressure_in": 29.83,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 86,
            "cloud": 24,
            "feelslike_c": 26.5,
            "feelslike_f": 79.6,
            "windchill_c": 24.3,
            "windchill_f": 75.7,
            "heatindex_c": 26.5,
            "heatindex_f": 79.6,
            "dewpoint_c": 21.7,
            "dewpoint_f": 71.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 7.1,
            "gust_kph": 11.4,
            "uv": 6.0
          },
          {
            "time_epoch": 1702258200,
            "time": "2023-12-11 07:00",
            "temp_c": 25.6,
            "temp_f": 78.0,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 74,
            "wind_dir": "ENE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.86,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 82,
            "cloud": 19,
            "feelslike_c": 28.0,
            "feelslike_f": 82.4,
            "windchill_c": 25.6,
            "windchill_f": 78.0,
            "heatindex_c": 28.0,
            "heatindex_f": 82.4,
            "dewpoint_c": 22.2,
            "dewpoint_f": 72.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 5.5,
            "gust_kph": 8.9,
            "uv": 7.0
          },
          {
            "time_epoch": 1702261800,
            "time": "2023-12-11 08:00",
            "temp_c": 27.6,
            "temp_f": 81.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.0,
            "wind_kph": 6.5,
            "wind_degree": 78,
            "wind_dir": "ENE",
            "pressure_mb": 1012.0,
            "pressure_in": 29.89,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 71,
            "cloud": 18,
            "feelslike_c": 30.3,
            "feelslike_f": 86.5,
            "windchill_c": 27.6,
            "windchill_f": 81.6,
            "heatindex_c": 30.3,
            "heatindex_f": 86.5,
            "dewpoint_c": 21.9,
            "dewpoint_f": 71.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.9,
            "gust_kph": 7.9,
            "uv": 7.0
          },
          {
            "time_epoch": 1702265400,
            "time": "2023-12-11 09:00",
            "temp_c": 29.5,
            "temp_f": 85.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 74,
            "wind_dir": "ENE",
            "pressure_mb": 1012.0,
            "pressure_in": 29.88,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 63,
            "cloud": 19,
            "feelslike_c": 32.6,
            "feelslike_f": 90.7,
            "windchill_c": 29.5,
            "windchill_f": 85.0,
            "heatindex_c": 32.6,
            "heatindex_f": 90.7,
            "dewpoint_c": 21.7,
            "dewpoint_f": 71.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 7.0
          },
          {
            "time_epoch": 1702269000,
            "time": "2023-12-11 10:00",
            "temp_c": 31.1,
            "temp_f": 88.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 68,
            "wind_dir": "ENE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.87,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 57,
            "cloud": 17,
            "feelslike_c": 34.8,
            "feelslike_f": 94.7,
            "windchill_c": 31.2,
            "windchill_f": 88.1,
            "heatindex_c": 34.8,
            "heatindex_f": 94.7,
            "dewpoint_c": 21.7,
            "dewpoint_f": 71.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.5,
            "gust_kph": 2.5,
            "uv": 8.0
          },
          {
            "time_epoch": 1702272600,
            "time": "2023-12-11 11:00",
            "temp_c": 32.3,
            "temp_f": 90.1,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 0.9,
            "wind_kph": 1.4,
            "wind_degree": 261,
            "wind_dir": "W",
            "pressure_mb": 1011.0,
            "pressure_in": 29.85,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 54,
            "cloud": 30,
            "feelslike_c": 36.3,
            "feelslike_f": 97.3,
            "windchill_c": 32.3,
            "windchill_f": 90.1,
            "heatindex_c": 36.3,
            "heatindex_f": 97.3,
            "dewpoint_c": 21.8,
            "dewpoint_f": 71.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.0,
            "gust_kph": 1.7,
            "uv": 8.0
          },
          {
            "time_epoch": 1702276200,
            "time": "2023-12-11 12:00",
            "temp_c": 32.4,
            "temp_f": 90.3,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 245,
            "wind_dir": "WSW",
            "pressure_mb": 1010.0,
            "pressure_in": 29.81,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 54,
            "cloud": 61,
            "feelslike_c": 36.5,
            "feelslike_f": 97.7,
            "windchill_c": 32.4,
            "windchill_f": 90.3,
            "heatindex_c": 36.5,
            "heatindex_f": 97.7,
            "dewpoint_c": 21.8,
            "dewpoint_f": 71.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 8.0
          },
          {
            "time_epoch": 1702279800,
            "time": "2023-12-11 13:00",
            "temp_c": 32.2,
            "temp_f": 89.9,
            "is_day": 1,
            "condition": {
              "text": "Patchy light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/263.png",
              "code": 1150
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 240,
            "wind_dir": "WSW",
            "pressure_mb": 1008.0,
            "pressure_in": 29.78,
            "precip_mm": 0.44,
            "precip_in": 0.02,
            "humidity": 55,
            "cloud": 52,
            "feelslike_c": 36.3,
            "feelslike_f": 97.4,
            "windchill_c": 32.2,
            "windchill_f": 89.9,
            "heatindex_c": 36.3,
            "heatindex_f": 97.4,
            "dewpoint_c": 21.9,
            "dewpoint_f": 71.4,
            "will_it_rain": 1,
            "chance_of_rain": 89,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 5.0,
            "vis_miles": 3.0,
            "gust_mph": 6.2,
            "gust_kph": 9.9,
            "uv": 7.0
          },
          {
            "time_epoch": 1702283400,
            "time": "2023-12-11 14:00",
            "temp_c": 31.0,
            "temp_f": 87.8,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 236,
            "wind_dir": "WSW",
            "pressure_mb": 1008.0,
            "pressure_in": 29.76,
            "precip_mm": 0.13,
            "precip_in": 0.01,
            "humidity": 60,
            "cloud": 53,
            "feelslike_c": 35.1,
            "feelslike_f": 95.2,
            "windchill_c": 31.0,
            "windchill_f": 87.8,
            "heatindex_c": 35.1,
            "heatindex_f": 95.2,
            "dewpoint_c": 22.4,
            "dewpoint_f": 72.2,
            "will_it_rain": 1,
            "chance_of_rain": 79,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 7.5,
            "gust_kph": 12.1,
            "uv": 7.0
          },
          {
            "time_epoch": 1702287000,
            "time": "2023-12-11 15:00",
            "temp_c": 29.0,
            "temp_f": 84.1,
            "is_day": 1,
            "condition": {
              "text": "Patchy light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/263.png",
              "code": 1150
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 229,
            "wind_dir": "SW",
            "pressure_mb": 1008.0,
            "pressure_in": 29.77,
            "precip_mm": 0.24,
            "precip_in": 0.01,
            "humidity": 71,
            "cloud": 52,
            "feelslike_c": 32.9,
            "feelslike_f": 91.2,
            "windchill_c": 29.0,
            "windchill_f": 84.1,
            "heatindex_c": 32.9,
            "heatindex_f": 91.2,
            "dewpoint_c": 23.1,
            "dewpoint_f": 73.6,
            "will_it_rain": 0,
            "chance_of_rain": 69,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 5.0,
            "vis_miles": 3.0,
            "gust_mph": 7.4,
            "gust_kph": 11.9,
            "uv": 6.0
          },
          {
            "time_epoch": 1702290600,
            "time": "2023-12-11 16:00",
            "temp_c": 28.6,
            "temp_f": 83.5,
            "is_day": 1,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 208,
            "wind_dir": "SSW",
            "pressure_mb": 1008.0,
            "pressure_in": 29.78,
            "precip_mm": 0.52,
            "precip_in": 0.02,
            "humidity": 74,
            "cloud": 54,
            "feelslike_c": 32.8,
            "feelslike_f": 91.0,
            "windchill_c": 28.6,
            "windchill_f": 83.5,
            "heatindex_c": 32.8,
            "heatindex_f": 91.0,
            "dewpoint_c": 23.6,
            "dewpoint_f": 74.5,
            "will_it_rain": 1,
            "chance_of_rain": 75,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 5.0,
            "gust_kph": 8.0,
            "uv": 6.0
          },
          {
            "time_epoch": 1702294200,
            "time": "2023-12-11 17:00",
            "temp_c": 27.5,
            "temp_f": 81.4,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 188,
            "wind_dir": "S",
            "pressure_mb": 1009.0,
            "pressure_in": 29.8,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 80,
            "cloud": 43,
            "feelslike_c": 31.3,
            "feelslike_f": 88.3,
            "windchill_c": 27.5,
            "windchill_f": 81.4,
            "heatindex_c": 31.3,
            "heatindex_f": 88.3,
            "dewpoint_c": 23.8,
            "dewpoint_f": 74.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.3,
            "gust_kph": 7.0,
            "uv": 7.0
          },
          {
            "time_epoch": 1702297800,
            "time": "2023-12-11 18:00",
            "temp_c": 26.3,
            "temp_f": 79.3,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 0.7,
            "wind_kph": 1.1,
            "wind_degree": 192,
            "wind_dir": "SSW",
            "pressure_mb": 1010.0,
            "pressure_in": 29.82,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 83,
            "cloud": 36,
            "feelslike_c": 29.3,
            "feelslike_f": 84.7,
            "windchill_c": 26.3,
            "windchill_f": 79.3,
            "heatindex_c": 29.3,
            "heatindex_f": 84.7,
            "dewpoint_c": 23.2,
            "dewpoint_f": 73.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.3,
            "gust_kph": 2.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1702301400,
            "time": "2023-12-11 19:00",
            "temp_c": 25.8,
            "temp_f": 78.5,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 1.1,
            "wind_kph": 1.8,
            "wind_degree": 359,
            "wind_dir": "N",
            "pressure_mb": 1011.0,
            "pressure_in": 29.84,
            "precip_mm": 0.04,
            "precip_in": 0.0,
            "humidity": 85,
            "cloud": 71,
            "feelslike_c": 28.7,
            "feelslike_f": 83.6,
            "windchill_c": 25.8,
            "windchill_f": 78.5,
            "heatindex_c": 28.7,
            "heatindex_f": 83.6,
            "dewpoint_c": 23.1,
            "dewpoint_f": 73.5,
            "will_it_rain": 0,
            "chance_of_rain": 60,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 2.1,
            "gust_kph": 3.4,
            "uv": 1.0
          },
          {
            "time_epoch": 1702305000,
            "time": "2023-12-11 20:00",
            "temp_c": 25.5,
            "temp_f": 77.9,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 29,
            "wind_dir": "NNE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.86,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 86,
            "cloud": 26,
            "feelslike_c": 28.2,
            "feelslike_f": 82.8,
            "windchill_c": 25.5,
            "windchill_f": 77.9,
            "heatindex_c": 28.2,
            "heatindex_f": 82.8,
            "dewpoint_c": 23.0,
            "dewpoint_f": 73.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.2,
            "gust_kph": 6.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1702308600,
            "time": "2023-12-11 21:00",
            "temp_c": 25.1,
            "temp_f": 77.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.0,
            "wind_kph": 3.2,
            "wind_degree": 40,
            "wind_dir": "NE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.87,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 87,
            "cloud": 21,
            "feelslike_c": 27.7,
            "feelslike_f": 81.8,
            "windchill_c": 25.1,
            "windchill_f": 77.1,
            "heatindex_c": 27.7,
            "heatindex_f": 81.8,
            "dewpoint_c": 22.8,
            "dewpoint_f": 73.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.9,
            "gust_kph": 6.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1702312200,
            "time": "2023-12-11 22:00",
            "temp_c": 24.8,
            "temp_f": 76.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.0,
            "wind_kph": 3.2,
            "wind_degree": 44,
            "wind_dir": "NE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.86,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 88,
            "cloud": 19,
            "feelslike_c": 27.3,
            "feelslike_f": 81.1,
            "windchill_c": 24.8,
            "windchill_f": 76.6,
            "heatindex_c": 27.3,
            "heatindex_f": 81.1,
            "dewpoint_c": 22.6,
            "dewpoint_f": 72.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.9,
            "gust_kph": 6.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1702315800,
            "time": "2023-12-11 23:00",
            "temp_c": 24.5,
            "temp_f": 76.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 51,
            "wind_dir": "NE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.84,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 88,
            "cloud": 21,
            "feelslike_c": 26.9,
            "feelslike_f": 80.3,
            "windchill_c": 24.5,
            "windchill_f": 76.1,
            "heatindex_c": 26.9,
            "heatindex_f": 80.3,
            "dewpoint_c": 22.3,
            "dewpoint_f": 72.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 5.2,
            "gust_kph": 8.4,
            "uv": 1.0
          }
        ]
      },
      {
        "date": "2023-12-12",
        "date_epoch": 1702339200,
        "day": {
          "maxtemp_c": 31.4,
          "maxtemp_f": 88.4,
          "mintemp_c": 23.5,
          "mintemp_f": 74.3,
          "avgtemp_c": 26.3,
          "avgtemp_f": 79.3,
          "maxwind_mph": 6.7,
          "maxwind_kph": 10.8,
          "totalprecip_mm": 2.2,
          "totalprecip_in": 0.09,
          "totalsnow_cm": 0.0,
          "avgvis_km": 9.8,
          "avgvis_miles": 6.0,
          "avghumidity": 78.0,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 76,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Patchy rain possible",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "code": 1063
          },
          "uv": 6.0
        },
        "astro": {
          "sunrise": "06:26 AM",
          "sunset": "06:05 PM",
          "moonrise": "05:36 AM",
          "moonset": "05:30 PM",
          "moon_phase": "New Moon",
          "moon_illumination": 1,
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1702319400,
            "time": "2023-12-12 00:00",
            "temp_c": 24.1,
            "temp_f": 75.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 61,
            "wind_dir": "ENE",
            "pressure_mb": 1010.0,
            "pressure_in": 29.83,
            "precip_mm": 0.22,
            "precip_in": 0.01,
            "humidity": 88,
            "cloud": 88,
            "feelslike_c": 26.4,
            "feelslike_f": 79.5,
            "windchill_c": 24.1,
            "windchill_f": 75.4,
            "heatindex_c": 26.4,
            "heatindex_f": 79.5,
            "dewpoint_c": 22.0,
            "dewpoint_f": 71.6,
            "will_it_rain": 1,
            "chance_of_rain": 75,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 6.2,
            "gust_kph": 10.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1702323000,
            "time": "2023-12-12 01:00",
            "temp_c": 23.8,
            "temp_f": 74.9,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 66,
            "wind_dir": "ENE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.8,
            "precip_mm": 0.2,
            "precip_in": 0.01,
            "humidity": 88,
            "cloud": 74,
            "feelslike_c": 26.0,
            "feelslike_f": 78.9,
            "windchill_c": 23.8,
            "windchill_f": 74.9,
            "heatindex_c": 26.0,
            "heatindex_f": 78.9,
            "dewpoint_c": 21.7,
            "dewpoint_f": 71.1,
            "will_it_rain": 0,
            "chance_of_rain": 63,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 6.7,
            "gust_kph": 10.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1702326600,
            "time": "2023-12-12 02:00",
            "temp_c": 23.7,
            "temp_f": 74.6,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 68,
            "wind_dir": "ENE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.79,
            "precip_mm": 0.21,
            "precip_in": 0.01,
            "humidity": 89,
            "cloud": 76,
            "feelslike_c": 25.9,
            "feelslike_f": 78.6,
            "windchill_c": 23.7,
            "windchill_f": 74.6,
            "heatindex_c": 25.9,
            "heatindex_f": 78.6,
            "dewpoint_c": 21.7,
            "dewpoint_f": 71.0,
            "will_it_rain": 1,
            "chance_of_rain": 74,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 7.1,
            "gust_kph": 11.4,
            "uv": 1.0
          },
          {
            "time_epoch": 1702330200,
            "time": "2023-12-12 03:00",
            "temp_c": 23.6,
            "temp_f": 74.5,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 67,
            "wind_dir": "ENE",
            "pressure_mb": 1009.0,
            "pressure_in": 29.78,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 89,
            "cloud": 38,
            "feelslike_c": 25.8,
            "feelslike_f": 78.5,
            "windchill_c": 23.6,
            "windchill_f": 74.6,
            "heatindex_c": 25.8,
            "heatindex_f": 78.5,
            "dewpoint_c": 21.7,
            "dewpoint_f": 71.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.1,
            "gust_kph": 9.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1702333800,
            "time": "2023-12-12 04:00",
            "temp_c": 23.6,
            "temp_f": 74.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 4.0,
            "wind_kph": 6.5,
            "wind_degree": 93,
            "wind_dir": "E",
            "pressure_mb": 1009.0,
            "pressure_in": 29.8,
            "precip_mm": 0.03,
            "precip_in": 0.0,
            "humidity": 89,
            "cloud": 81,
            "feelslike_c": 25.8,
            "feelslike_f": 78.5,
            "windchill_c": 23.6,
            "windchill_f": 74.4,
            "heatindex_c": 25.8,
            "heatindex_f": 78.5,
            "dewpoint_c": 21.7,
            "dewpoint_f": 71.1,
            "will_it_rain": 1,
            "chance_of_rain": 76,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 7.9,
            "gust_kph": 12.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1702337400,
            "time": "2023-12-12 05:00",
            "temp_c": 23.6,
            "temp_f": 74.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 93,
            "wind_dir": "E",
            "pressure_mb": 1009.0,
            "pressure_in": 29.81,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 89,
            "cloud": 13,
            "feelslike_c": 25.8,
            "feelslike_f": 78.5,
            "windchill_c": 23.6,
            "windchill_f": 74.5,
            "heatindex_c": 25.8,
            "heatindex_f": 78.5,
            "dewpoint_c": 21.7,
            "dewpoint_f": 71.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.9,
            "gust_kph": 11.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1702341000,
            "time": "2023-12-12 06:00",
            "temp_c": 23.5,
            "temp_f": 74.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 88,
            "wind_dir": "E",
            "pressure_mb": 1010.0,
            "pressure_in": 29.83,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 89,
            "cloud": 15,
            "feelslike_c": 25.7,
            "feelslike_f": 78.3,
            "windchill_c": 23.5,
            "windchill_f": 74.3,
            "heatindex_c": 25.7,
            "heatindex_f": 78.3,
            "dewpoint_c": 21.7,
            "dewpoint_f": 71.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 7.3,
            "gust_kph": 11.8,
            "uv": 6.0
          },
          {
            "time_epoch": 1702344600,
            "time": "2023-12-12 07:00",
            "temp_c": 24.9,
            "temp_f": 76.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 86,
            "wind_dir": "E",
            "pressure_mb": 1011.0,
            "pressure_in": 29.85,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 86,
            "cloud": 23,
            "feelslike_c": 27.2,
            "feelslike_f": 81.0,
            "windchill_c": 24.9,
            "windchill_f": 76.7,
            "heatindex_c": 27.2,
            "heatindex_f": 81.0,
            "dewpoint_c": 22.3,
            "dewpoint_f": 72.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 5.3,
            "gust_kph": 8.5,
            "uv": 6.0
          },
          {
            "time_epoch": 1702348200,
            "time": "2023-12-12 08:00",
            "temp_c": 26.3,
            "temp_f": 79.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 72,
            "wind_dir": "ENE",
            "pressure_mb": 1012.0,
            "pressure_in": 29.87,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 78,
            "cloud": 18,
            "feelslike_c": 28.8,
            "feelslike_f": 83.8,
            "windchill_c": 26.3,
            "windchill_f": 79.3,
            "heatindex_c": 28.8,
            "heatindex_f": 83.8,
            "dewpoint_c": 22.1,
            "dewpoint_f": 71.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.6,
            "gust_kph": 7.5,
            "uv": 7.0
          },
          {
            "time_epoch": 1702351800,
            "time": "2023-12-12 09:00",
            "temp_c": 27.6,
            "temp_f": 81.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 98,
            "wind_dir": "E",
            "pressure_mb": 1012.0,
            "pressure_in": 29.89,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 70,
            "cloud": 23,
            "feelslike_c": 30.3,
            "feelslike_f": 86.5,
            "windchill_c": 27.7,
            "windchill_f": 81.8,
            "heatindex_c": 30.3,
            "heatindex_f": 86.5,
            "dewpoint_c": 21.7,
            "dewpoint_f": 71.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 5.1,
            "gust_kph": 8.1,
            "uv": 7.0
          },
          {
            "time_epoch": 1702355400,
            "time": "2023-12-12 10:00",
            "temp_c": 29.5,
            "temp_f": 85.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 119,
            "wind_dir": "ESE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.86,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 62,
            "cloud": 24,
            "feelslike_c": 32.4,
            "feelslike_f": 90.4,
            "windchill_c": 29.5,
            "windchill_f": 85.1,
            "heatindex_c": 32.4,
            "heatindex_f": 90.4,
            "dewpoint_c": 21.4,
            "dewpoint_f": 70.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 7.0
          },
          {
            "time_epoch": 1702359000,
            "time": "2023-12-12 11:00",
            "temp_c": 31.1,
            "temp_f": 87.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 1.6,
            "wind_kph": 2.5,
            "wind_degree": 165,
            "wind_dir": "SSE",
            "pressure_mb": 1010.0,
            "pressure_in": 29.84,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 57,
            "cloud": 13,
            "feelslike_c": 34.5,
            "feelslike_f": 94.2,
            "windchill_c": 31.1,
            "windchill_f": 87.9,
            "heatindex_c": 34.5,
            "heatindex_f": 94.2,
            "dewpoint_c": 21.5,
            "dewpoint_f": 70.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.8,
            "gust_kph": 2.9,
            "uv": 8.0
          },
          {
            "time_epoch": 1702362600,
            "time": "2023-12-12 12:00",
            "temp_c": 31.4,
            "temp_f": 88.4,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 216,
            "wind_dir": "SW",
            "pressure_mb": 1009.0,
            "pressure_in": 29.81,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 55,
            "cloud": 51,
            "feelslike_c": 34.8,
            "feelslike_f": 94.7,
            "windchill_c": 31.4,
            "windchill_f": 88.4,
            "heatindex_c": 34.8,
            "heatindex_f": 94.7,
            "dewpoint_c": 21.4,
            "dewpoint_f": 70.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 8.0
          },
          {
            "time_epoch": 1702366200,
            "time": "2023-12-12 13:00",
            "temp_c": 31.2,
            "temp_f": 88.1,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 218,
            "wind_dir": "SW",
            "pressure_mb": 1008.0,
            "pressure_in": 29.77,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 57,
            "cloud": 74,
            "feelslike_c": 34.8,
            "feelslike_f": 94.6,
            "windchill_c": 31.2,
            "windchill_f": 88.1,
            "heatindex_c": 34.8,
            "heatindex_f": 94.6,
            "dewpoint_c": 21.6,
            "dewpoint_f": 70.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.7,
            "gust_kph": 10.8,
            "uv": 7.0
          },
          {
            "time_epoch": 1702369800,
            "time": "2023-12-12 14:00",
            "temp_c": 29.8,
            "temp_f": 85.7,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 225,
            "wind_dir": "SW",
            "pressure_mb": 1008.0,
            "pressure_in": 29.75,
            "precip_mm": 0.09,
            "precip_in": 0.0,
            "humidity": 64,
            "cloud": 51,
            "feelslike_c": 33.5,
            "feelslike_f": 92.2,
            "windchill_c": 29.9,
            "windchill_f": 85.7,
            "heatindex_c": 33.5,
            "heatindex_f": 92.2,
            "dewpoint_c": 22.3,
            "dewpoint_f": 72.1,
            "will_it_rain": 1,
            "chance_of_rain": 76,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.0,
            "gust_kph": 12.9,
            "uv": 6.0
          },
          {
            "time_epoch": 1702373400,
            "time": "2023-12-12 15:00",
            "temp_c": 28.5,
            "temp_f": 83.4,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 6.0,
            "wind_kph": 9.7,
            "wind_degree": 232,
            "wind_dir": "SW",
            "pressure_mb": 1008.0,
            "pressure_in": 29.75,
            "precip_mm": 0.34,
            "precip_in": 0.01,
            "humidity": 72,
            "cloud": 82,
            "feelslike_c": 32.2,
            "feelslike_f": 90.0,
            "windchill_c": 28.5,
            "windchill_f": 83.4,
            "heatindex_c": 32.2,
            "heatindex_f": 90.0,
            "dewpoint_c": 23.0,
            "dewpoint_f": 73.4,
            "will_it_rain": 1,
            "chance_of_rain": 76,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 8.1,
            "gust_kph": 13.1,
            "uv": 6.0
          },
          {
            "time_epoch": 1702377000,
            "time": "2023-12-12 16:00",
            "temp_c": 28.1,
            "temp_f": 82.6,
            "is_day": 1,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 227,
            "wind_dir": "SW",
            "pressure_mb": 1008.0,
            "pressure_in": 29.76,
            "precip_mm": 0.76,
            "precip_in": 0.03,
            "humidity": 75,
            "cloud": 51,
            "feelslike_c": 31.8,
            "feelslike_f": 89.2,
            "windchill_c": 28.1,
            "windchill_f": 82.6,
            "heatindex_c": 31.8,
            "heatindex_f": 89.2,
            "dewpoint_c": 23.2,
            "dewpoint_f": 73.7,
            "will_it_rain": 1,
            "chance_of_rain": 73,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 5.8,
            "gust_kph": 9.4,
            "uv": 6.0
          },
          {
            "time_epoch": 1702380600,
            "time": "2023-12-12 17:00",
            "temp_c": 27.2,
            "temp_f": 81.0,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 2.9,
            "wind_kph": 4.7,
            "wind_degree": 231,
            "wind_dir": "SW",
            "pressure_mb": 1009.0,
            "pressure_in": 29.78,
            "precip_mm": 0.12,
            "precip_in": 0.0,
            "humidity": 79,
            "cloud": 73,
            "feelslike_c": 30.6,
            "feelslike_f": 87.0,
            "windchill_c": 27.2,
            "windchill_f": 81.0,
            "heatindex_c": 30.6,
            "heatindex_f": 87.0,
            "dewpoint_c": 23.2,
            "dewpoint_f": 73.8,
            "will_it_rain": 0,
            "chance_of_rain": 66,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.5,
            "gust_kph": 7.3,
            "uv": 6.0
          },
          {
            "time_epoch": 1702384200,
            "time": "2023-12-12 18:00",
            "temp_c": 25.9,
            "temp_f": 78.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 236,
            "wind_dir": "WSW",
            "pressure_mb": 1009.0,
            "pressure_in": 29.8,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 82,
            "cloud": 22,
            "feelslike_c": 28.5,
            "feelslike_f": 83.3,
            "windchill_c": 25.9,
            "windchill_f": 78.6,
            "heatindex_c": 28.5,
            "heatindex_f": 83.3,
            "dewpoint_c": 22.5,
            "dewpoint_f": 72.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 2.4,
            "gust_kph": 3.9,
            "uv": 1.0
          },
          {
            "time_epoch": 1702387800,
            "time": "2023-12-12 19:00",
            "temp_c": 25.5,
            "temp_f": 78.0,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 0.9,
            "wind_kph": 1.4,
            "wind_degree": 15,
            "wind_dir": "NNE",
            "pressure_mb": 1010.0,
            "pressure_in": 29.82,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 83,
            "cloud": 23,
            "feelslike_c": 28.1,
            "feelslike_f": 82.5,
            "windchill_c": 25.5,
            "windchill_f": 78.0,
            "heatindex_c": 28.1,
            "heatindex_f": 82.5,
            "dewpoint_c": 22.5,
            "dewpoint_f": 72.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.6,
            "gust_kph": 2.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1702391400,
            "time": "2023-12-12 20:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 1.8,
            "wind_kph": 2.9,
            "wind_degree": 31,
            "wind_dir": "NNE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.85,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 85,
            "cloud": 23,
            "feelslike_c": 27.7,
            "feelslike_f": 81.8,
            "windchill_c": 25.2,
            "windchill_f": 77.4,
            "heatindex_c": 27.7,
            "heatindex_f": 81.8,
            "dewpoint_c": 22.4,
            "dewpoint_f": 72.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.3,
            "gust_kph": 5.3,
            "uv": 1.0
          },
          {
            "time_epoch": 1702395000,
            "time": "2023-12-12 21:00",
            "temp_c": 24.7,
            "temp_f": 76.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 38,
            "wind_dir": "NE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.86,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 86,
            "cloud": 24,
            "feelslike_c": 27.0,
            "feelslike_f": 80.7,
            "windchill_c": 24.7,
            "windchill_f": 76.5,
            "heatindex_c": 27.0,
            "heatindex_f": 80.7,
            "dewpoint_c": 22.2,
            "dewpoint_f": 72.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 5.1,
            "gust_kph": 8.1,
            "uv": 1.0
          },
          {
            "time_epoch": 1702398600,
            "time": "2023-12-12 22:00",
            "temp_c": 24.3,
            "temp_f": 75.7,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 49,
            "wind_dir": "NE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.86,
            "precip_mm": 0.24,
            "precip_in": 0.01,
            "humidity": 87,
            "cloud": 87,
            "feelslike_c": 26.5,
            "feelslike_f": 79.8,
            "windchill_c": 24.3,
            "windchill_f": 75.7,
            "heatindex_c": 26.5,
            "heatindex_f": 79.8,
            "dewpoint_c": 22.0,
            "dewpoint_f": 71.6,
            "will_it_rain": 0,
            "chance_of_rain": 69,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 6.0,
            "gust_kph": 9.7,
            "uv": 1.0
          },
          {
            "time_epoch": 1702402200,
            "time": "2023-12-12 23:00",
            "temp_c": 24.1,
            "temp_f": 75.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 63,
            "wind_dir": "ENE",
            "pressure_mb": 1011.0,
            "pressure_in": 29.84,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 87,
            "cloud": 21,
            "feelslike_c": 26.3,
            "feelslike_f": 79.3,
            "windchill_c": 24.1,
            "windchill_f": 75.3,
            "heatindex_c": 26.3,
            "heatindex_f": 79.3,
            "dewpoint_c": 21.8,
            "dewpoint_f": 71.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 7.0,
            "gust_kph": 11.2,
            "uv": 1.0
          }
        ]
      }
    ]
  }
};
